### ISSUE TITLE
Linux bug fix : who -s return :0 

### ISSUE THREAD

**Issue by lynch4fr** [BoboTiG/pombo#12]
Salut,
En retour de la commande who -s dans le programme ligne 246, j'ai un cas different de 'tty' ou 'pts' et le split ne marche pas :

    who -s
    santoine :0           2017-04-20 08:27 (:0)**

J'ai donc dû ajouter un cas supplementaire :

                 ̶i̶f̶ ̶'̶t̶t̶y̶'̶ ̶i̶n̶ ̶l̶i̶n̶e̶ ̶o̶r̶ ̶'̶p̶t̶s̶'̶ ̶i̶n̶ ̶l̶i̶n̶e̶:̶
                if 'tty' in line or 'pts' in line or ':0' in line:
                    user = line.split(' ')[0]
                     ̶i̶f̶ ̶'̶(̶:̶0̶)̶'̶ ̶i̶n̶ ̶l̶i̶n̶e̶:̶
                    if ':0' in line:
                        break

 Vous pouvez rajouter cela dans une prochaine release +1: 
Merci pour ce super programme

**Comment by BoboTiG** [comment]
Salut,

Oui, j'ajouterai le fix prochainement. Merci :)

**Comment by BoboTiG** [comment]
Salut,

Si tu te sens d'attaque après plus d'1 an, je ne serai pas contre une petite PR pour fixer le problème :)
