### ISSUE TITLE
silent screenshot and launch on boot

### ISSUE THREAD

**Issue by Anard** [BoboTiG/pombo#15]
Hi. First thanks so much for this work.
I found a little "error" in pombo.conf for Linux import commands : it rings a bell when taking the screenshot.
I's better adding the option -silent to import command : 
```
; [L] /usr/bin/import -silent -window root <filepath>
; [L] /usr/bin/import -silent -display :0 -window root -quality 50 <filepath>
; [L] /usr/bin/import -silent -display :1 -window root -quality 50 <filepath>
; [L] /usr/bin/import -silent -display :0.0 -window root -quality 50 <filepath>
```

A second problem is that pombo is launched every 15 minutes after boot. Even if a thief boots the computer with an autologin session, it's possible he'll shut it off before 15 minutes.
For preventing this, I add in root's crontab : 
```
@startup /usr/local/bin/pombo
```

**Comment by BoboTiG** [comment]
Hello,

Thank you for the information. do you mind opening a PR to make those changes available for everyone?

**Comment by Anard** [comment]
No problem but I'm new to github, and don't know how to...
