### ISSUE TITLE
GPS tracking

### ISSUE THREAD

**Issue by erelsgl** [BoboTiG/pombo#21]
Small question... If I install Pombo on a device with GPS, will it send the GPS information to the server so that I can locate the device in case it is stolen?

**Comment by BoboTiG** [comment]
As of now: no.
But it could be a great add to the project. Do you have a command line for retrieving such data?

**Comment by erelsgl** [comment]
I don't know about a command line interface.
In Python I found this: http://smartphonedaq.com/gps.page
but it seems to work only for Android.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by BoboTiG** [comment]
It is not common to have a GPS device onto your computer.
I am closing the issue as it is related to Android, a platform Pombo does not run on.

One possible solution (if you have any GPS device on your compuer) is to find command lines to retreive lat/lon information. If you can manage this step, we will be able to add the feature in Pombo.

BTW thanks for the interest :)

**Comment by pshobowale** [comment]
I would like to reopen this issue as it might be a nice tool for the Pinephone

**Comment by BoboTiG** [comment]
If you can answer to my questions, then I'll reopen. I do not plan to do something on my end as I do not have anything that can help moving forward.
