### ISSUE TITLE
only one '-' allowed in IP Address

### ISSUE THREAD

**Issue by vsboost** [BoboTiG/pombo#22]
Hi there,

Trying to test and get the error below

only one '-' allowed in IP Address
Test cannot continue ...
Session terminated.

**Comment by BoboTiG** [comment]
Could you post the full error please?
What OS?

**Comment by BoboTiG** [comment]
And what is the response you get when calling the server's URL like:
```
$SERVER_URL/?myip=1
```

**Comment by vsboost** [comment]
All good, i worked out that needed to include pombo.php in the full server url.
