### ISSUE TITLE
How to disable a command

### ISSUE THREAD

**Issue by InfoLibre** [BoboTiG/pombo#24]
On http://bobotig.fr/index.php?c=projets/pombo/ , it's written "pour désactiver une commande, mettez-la à False.". In pombo.conf, it's written "To disable a command, blank it". Which is right ?
I must blank all the line or only words after = 
For example : gpg_binary=C:\\pombo\\bin\\gpg.exe -> gpg_binary=

**Comment by BoboTiG** [comment]
`pombo.conf` is the most up-to-date file ad so it is right :)
