### ISSUE TITLE
Update or install 1.0.3 -> 1.1b1

### ISSUE THREAD

**Issue by lynch4fr** [BoboTiG/pombo#36]
Hello,
What is the best way to test and update my pombo 1.0.3 to 1.1b1 on Windows ? 
```
c:\pombo\Pombo - Update.bat
_Pombo 1.0.3                                                                                                                     
 - Development version available: 1.1b1                                                                                         
 . You should upgrade only for tests purpose!                                                                                   
 - Check https://github.com/BoboTiG/pombo                                                                                       
   and report issues/ideas on GitHub_    
```

Thanks a lot
Lynch4

**Comment by lynch4fr** [comment]
I have the impression that launching pombo by the key register does not work for me? I declare the stolen computer by creating a .stolen file and nothing happens!
Whereas we contradict when launching it manually: pombo / svchost.exe pombo.py the behavior is normal.
How can we test the correct launch of VBS? Please. Thank you.

**Comment by BoboTiG** [comment]
As there is no installer for beta versions, you could simply replace `c:\pombo^pombo.py` with https://github.com/BoboTiG/pombo/blob/master/pombo.py. But I do not recommend to do it :)

**Comment by lynch4fr** [comment]
- Thanks, I'll try this.

- For my second question: I looked at the registry key that starts Pombo at startup ... shouldn't this key be launched this VBS with a command ?

cscript.exe C: \ pombostart.vbs ?
or
WScript.exe C: \ pombostart.vbs ?

Thanks :)
