### ISSUE TITLE
[ubuntu] Screenshots not working

### ISSUE THREAD

**Issue by rominail** [BoboTiG/pombo#43]
I checked if pombo was running correctly, it's almost working except the screenshot part.
After looking through the code I might figured out the problem : 
In the screenshot function of the final binary the "%d" seems not to be replaced by anything and then the % symbol pose problem for zipping (hence not zipped)
I replaced the code by the code below which seems to work after reading the mss documentation at [https://python-mss.readthedocs.io/api.html?highlight=save#mss.base.MSSBase.save](https://python-mss.readthedocs.io/api.html?highlight=save#mss.base.MSSBase.save)
(There is probably a way to make the code cleaner, I'm not really good in python)
```
filepath = "{}_screenshot".format(os.path.join(temp, filename))
filepath = filepath + "_{mon}.png"
```

Details :
Pombo 1.1b1
I am using Python 3.10.6
            & MSS 7.0.1
            & IPy 1.01
        & request 2.25.1
On Ubuntu 22.04.2 LTS

I can give more informations if needed

**Comment by BoboTiG** [comment]
Oh you're right!

Can you confirm it works when you just change that line: https://github.com/BoboTiG/pombo/blob/d4adb067f1c7822a6f79b31e83138a33cbc04ee6/pombo.py#L604
to
```python
 filepath = f"{os.path.join(temp, filename)}_screenshot-{mon}.png"
```
?

**Comment by rominail** [comment]
Running with sudo pombo check :
```
name 'mon' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/pombo", line 1078, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/pombo", line 1065, in main
    pombo.work()
  File "/usr/local/bin/pombo", line 880, in work
    self.snapshot(current_ip)
  File "/usr/local/bin/pombo", line 662, in snapshot
    filestozip.extend(self.screenshot(report_name))
  File "/usr/local/bin/pombo", line 604, in screenshot
    filepath = f"{os.path.join(temp, filename)}_screenshot-{mon}.png"
NameError: name 'mon' is not defined. Did you mean: 'min'?
```

**Comment by BoboTiG** [comment]
My bad, it I forgot to escape:
```python
 filepath = f"{os.path.join(temp, filename)}_screenshot-{{mon}}.png"
```

**Comment by BoboTiG** [comment]
I'll need to fix the code directly.
If you want to give a try, I'll be happy to merge a pull request ;)

**Comment by rominail** [comment]
I opened a PR
