### ISSUE TITLE
Client for mobile devices?

### ISSUE THREAD

**Issue by rolodato** [BoboTiG/pombo#9]
Hi @BoboTiG, Pombo looks great! I haven't started using it yet, but wanted to ask if it would make sense (or if it's even possible) to write clients for iOS and/or Android. It would be great to be able to use Pombo across all my devices. Thanks!

**Comment by BoboTiG** [comment]
Hi @rolodato, unfortunately Python is not installed on all these devices by default. Moreover, it will be too complex for me to try something or even port the code to iOS/Android: I do not have required skills.

**Comment by rolodato** [comment]
No worries, thanks for the confirmation :)
